# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170212_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
